[url]
url = "https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv"
destination_folder = '/tmp'
file_name = 'inventory.csv'


[destination]
destination_folder = '/tmp'
file_name = 'inventory.csv'

[snowflake]
warehouse = 'COMPUTE_WH'
database = 'TPCDS' 
schema =  'RAW'
file_format_name = 'comma_csv'
stage_name = "inventory_stage"
table = "inventory"